#!/bin/bash

#fix path
echo "export PATH=/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" >> ~/.bashrc
export "VAULT_ADDR=http://127.0.0.1:8200" >> ~/.bashrc
echo "alias k='kubectl'" >> ~/.bashrc
#k8s setup
echo "Setting up K8s..."
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc
/usr/bin/start.sh
echo "K8s setup complete"


curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

apt update -y
apt install -y kubectl 
apt install -y consul 
apt install -y vault

git clone https://github.com/Andrew-Klaas/instruqt-tokenization-lab.git 
cp -r instruqt-tokenization-lab /root
 cp -r /root/instruqt-tokenization-lab/assets/helm /root/

/usr/local/bin/helm repo add stable https://charts.helm.sh/stable
/usr/local/bin/helm repo add hashicorp https://helm.releases.hashicorp.com
/usr/local/bin/helm repo add bitnami https://charts.bitnami.com/bitnami
/usr/local/bin/helm repo update

/usr/local/bin/helm install pq \
  --set postgresqlPassword=password,postgresqlDatabase=vault_go_demo \
    bitnami/postgresql -f /root/helm/postgresql-values.yaml
/usr/local/bin/helm install vault hashicorp/vault -f /root/helm/vault-values.yaml

sleep 60s

export VAULT_ADDR=http://127.0.0.1:8200
/usr/bin/vault login root

cat << EOF > transform-app-example.policy
path "*" {
    capabilities = ["read", "list", "create", "update", "delete"]
}
path "transform/*" {
    capabilities = ["read", "list", "create", "update", "delete"]
}
EOF
vault policy write transform-app-example transform-app-example.policy

